### ISSUE TITLE
Posibilidad de poner "Propuestas de mejora" a las soluciones

### ISSUE THREAD

**Issue by messianos** [messianos/pci_server#10]
En el futuro podriamos agregar la opcion de plantear mejoras a las soluciones para evitar soluciones similares y para incentivar la busqueda de una solucion "en comunidad" y no individual.

**Comment by federicojasson** [comment]
Agrego:

Las propuestas de cambios podrían mostrarse junto a la solución, y ser calificadas por los usuarios.
