### ISSUE TITLE
Auto format del código

### ISSUE THREAD

**Issue by federicojasson** [messianos/pci_server#13]
¿Podrás configurar el auto formatter para que no haga wrap del código?
Lo está wrappeando bastante corto y lo hace menos legible (en mi opinión).

Ejemplo:
        user->birth_date = new Date("%d-%m-%Y",
                form_info.birth_date.value().c_str());

No parece una línea tan larga.

**Comment by messianos** [comment]
si es verdad, cdo hagas el commit veo si se guarda en el git cambiandolo en el eclipse

**Comment by messianos** [comment]
si por suerte se guarda en git, asiq desp de q comitees lo cambio, o si sabes ponelo vos. Project Props -> Formatter -> New -> Line Wrapping: 120
