### ISSUE TITLE
Ordenamiento de "src"

### ISSUE THREAD

**Issue by federicojasson** [messianos/pci_server#18]
Se me ocurre una posible forma de organizar el directorio "src":

--------- Logica (src/logic/)
Main
Server
ViewContent

--------- Clases de entidades (src/entity/)
Problem
Publication
Solution
User
Clarification

--------- Clases de servicio (/src/service/)
PasswordManager
InputValidator
IDManager
DatabaseInterface

--------- Clases auxiliares (/src/auxiliar/)
ErrorCode
Date
Datetime

¿Opiniones?

**Comment by messianos** [comment]
wonderful
