### ISSUE TITLE
TODO List in Gist

### ISSUE THREAD

**Issue by messianos** [messianos/pci_server#22]
Gist es una aplicacion de github para poner "pastes" o "snippets", se pueden editar y son como los repositorios, se versionan! jaja aca pongo el todo q estaba en el collab...

https://gist.github.com/messianos/96d5c2c194a8837b9de2

**Comment by federicojasson** [comment]
¿Cómo se edita?

**Comment by messianos** [comment]
no se puede, es una cagada.
