### ISSUE TITLE
Auto-votos

### ISSUE THREAD

**Issue by federicojasson** [messianos/pci_server#23]
Me quedó una duda pendiente: ¿un usuario puede auto-votarse su propia publicación?

Estoy con la documentación, y es importante definirlo claramente ahora.

**Comment by messianos** [comment]
Yo diria que no, pero no tengo argumentos muy firmes. No tiene sentido que
pueda votarse me parece, aunque si lo hiciera no cambiaria mucho tampoco.

**Comment by GNZ** [comment]
No posta que no tiene sentido que se autovote. Otra cosa, que seleccione su solución como aceptada?? tiene sentido porque puede haber descubierto como solucionar el problema, pero que no suba ranking.

**Comment by federicojasson** [comment]
Listo, de acuerdo con ustedes.
