### ISSUE TITLE
Pagina de inicio

### ISSUE THREAD

**Issue by messianos** [messianos/pci_server#4]
Que hacemos? La hacemos aparecer cuando el usuario no este registrado tipo FB? Con el form de signup...

No le veo sentido a que este cdo el usuario esta registrado, es como entrar a FB y que te preg si queres ir a noticias o grupos...

**Comment by federicojasson** [comment]
Lo del signup me gusta.
Respecto a lo otro, tal vez se podría diseñar un menú inicial para que el usuario decida ir hacia "Problemas" o "Ideas".

**Comment by messianos** [comment]
Para mi no tiene sentido esa division, esta hecha adentro, es como el ej q puse del fb, no te parece?

**Comment by federicojasson** [comment]
Pero... si está logueado el usuario, a dónde lo manda, a problemas o a ideas??

**Comment by messianos** [comment]
Problemas, o lo que tenga en "sus preferencias".

Hay algo q es seguro, no va a querer elegir cada vez q entra. O no?

Podemos presentar el menu para elegir y poner un tilde estilo "recordar" tmb.

**Comment by federicojasson** [comment]
Te puedo pedir que dejes de sacarme el index del mapper?? No me dejás trabajar en la portada. Gracias

**Comment by messianos** [comment]
Bueno, pero pone una forma de acceder a los problemas! un link choto aunq sea, no se puede salir del index
