### ISSUE TITLE
Generalizacion de main content

### ISSUE THREAD

**Issue by messianos** [messianos/pci_server#7]
Para las paginas:

SignUp
NewProblem
Problems

Tendria que haber un main content generalizado, no instanciado (pci_signup_main_content_container, pci_problems_main_content_container, etc) , en este momento NewProblem no tiene la cajita blanca de fondo.

**Comment by federicojasson** [comment]
Ése era uno de los cambios que me habías hecho. Por favor, no lo vuelvas a generalizar.
Razones:

-Está bueno que las páginas tengan cierta independencia. Sí, puede que en este caso particular ALGUNAS coincidan (sin embargo no todas necesariamente van a tener, por ejemplo, el menú de navegación a la izquierda, lo cual implicaría un padding distinto).
-Generalizar demasiado te hace cometer cambios inesperados. Por ejemplo: el hecho de que reutilizaras un cierto pci_box_X en varios lugares me dio un dolor de cabeza ayer, porque cambié un padding en un lugar y se me cambió en varios otros sin darme cuenta.

**Comment by messianos** [comment]
El main content (cajita con fondo blanco y puntas redondeadas) esta en muchos (casi todos) los templates, ahi no veo el sentido de no generalizar.

Esto:

#pci_problem_main_container {
    min-width:912px;
    padding:64px 128px 0px 240px;
}

esta repetido en casi todos los css, cdo querramos cambiar va a ser un dolor de huevos.

Lo de los boxes es verdad, para no tocarte tanto te use los tuyos, sino tenia q agregar mas codigo.

Al margen:
Porque tienen nombres tan poco descriptivos los boxes y botones? Es un todo? Recien queria poner uno y no sabia cual usar :P

**Comment by federicojasson** [comment]
1-  El main_container no es la cajita con puntas redondeadas (eso es del pci_box que tenga adentro). Se supone que maneje el padding y otras cuestiones de layout (no visibles).

2- Entiendo lo que decís de lo de los cambios, pero bueno, yo lo había pensado imaginándome que en ciertas páginas podría haber diferencias. Por ejemplo, imaginate que en Problems mañana se nos ocurre agregar un menú de navegación a la derecha (más allá del que ya existe en la izquierda). En ese caso tendrías que cambiar el padding de la derecha del main_container. Ahora bien, si generalizás se te va a cambiar en todos lados, y el menú de navegación de la derecha sólo va a estar en Problems. En conclusión, me parece que, por lo menos en la etapa del diseño en la que estamos, es mejor dejar la independencia para hacer adaptaciones más rápidas. Si en el diseño definitivo se llega a la conclusión de que en todos lados se usa el main_container de la misma forma, podemos generalizar.

3- Lo de los nombres no hay ninguna razón en particular. La idea era que los nombres no identificaran la "posición" del elemento en cuestión. Por ejemplo, poner pci_button_header_bar implicaría que es un botón del header_bar. Puede que sea así, que sea del header_bar, pero que también quieras usar ese tipo de botón en otro lado. Nada más que por eso.

**Comment by messianos** [comment]
1. Es verdad me habia olvidado, lo q decia de generalizar es el blanco con ptas red
2. Esta bien lo que decis, pero me parece que tiene q ser al reves, primero generalizar y despues si hay un caso particular cambiar y el nombre y listo. Pero ya esta hecho asi, queda asi.
3. No hay una respuesta absolutamente correcta, pero me parece mejor ponerle "de ultima" la ubicacion para no tener q leer e interpretar el codigo css del boton para saber q boton es x ej. Tambien se podria poner en el nombre algun aspecto del diseño (aunque pueda cambiar, da una idea inmediata de que se trata, ej "wide_red_button")

Sigamos usando este medio para cualquier duda, asi las solucionamos y quedan asentadas.
