### ISSUE TITLE
Color del header

### ISSUE THREAD

**Issue by messianos** [messianos/pci_server#8]
Fede:

Porque el header ahora es rojo, si habiamos quedado en que era azul?

No cambiemos cosas que decidimos entre todos sin consultar.

**Comment by federicojasson** [comment]
Estaba viendo anoche cómo quedaba otra combinación de colores y me olvidé cambiarlo antes del commit (está comentado en el CSS los colores que habíamos quedado).

Nota al margen: no me gusta la estética de la página todavía.

**Comment by messianos** [comment]
ok ok, si esta muy muerta.

Hay que esperar que se llene igual.

"Problem description 14 / 11 / 90" no es algo muy lindo q digamos, eso va a ir avanzando, cdo tenga iconos y demas...

Por eso me parece q no le tenemos q dar tanta bola al css, yo ahora hice "Plantear Solucion" con los divs necesarios para que se vea y se pueda apretar nomas, tendriamos que terminar todo y desp ponernos todos juntos a probar.
