### ISSUE TITLE
¿Los problemas deberían tener un título?

### ISSUE THREAD

**Issue by federicojasson** [messianos/pci_server#9]
Se me ocurre que, tal vez, los problemas podrían tener un título (más allá de la breve descripción que ya tienen).

Lo dejo planteado para no olvidarnos, no para hacerlo YA.

**Comment by messianos** [comment]
Yo asumia como tiutlo la descripcion general, tipo StackOverflow. Es muy dificil encontrar un titulo, no te parece? Una descripcion es menos formal y mas rapida de hacer, sin pensar tanto. (no le pusimos titulo a nuestra pag :P se llama PCI que es una descripcion jaja)

**Comment by federicojasson** [comment]
StackOverflow tiene títulos (lo que yo entiendo por títulos jajaja). Pero bueno, si es una cuestión de nombres todo bien.

**Comment by GNZ** [comment]
Comparto con Fede, deberían tener un titulo y luego la descripción (o una parte de ella).

**Comment by messianos** [comment]
Estamos llamando de la misma manera al titulo y a la descripcion general. Titulo + descr gral + descripcion completa no va para mi, no les parece?
